Focus failures
tsdataclinic/scout pull request #307
Opened 2022-08-02 19:25 UTC by Detroit-the-Dev

## Summary

Please include a summary of the changes. Also include relevant motivation and context. List any dependencies that are required for this change.

Keyboard users who use the tab key to navigate through page aren't able to see which dataset they are focused on on the page. The elements ARE focused but not visibly; updated to include outline for visual tracking.

## Screenshots or Videos (if applicable)

Include screenshots or video recordings to show off your change (if applicable).

Attached screenshots of dataset links, before AND after outline added.
![Dataset Link With Outline](https://user-images.githubusercontent.com/70827740/182456413-9ca1119f-0dbd-4cc9-ad29-c6db86b58654.jpeg)
<img width="1440" alt="Before Dataset Link Outline" src="https://user-images.githubusercontent.com/70827740/182456424-5b7493c6-881a-4a50-93c6-a7a631357be5.png">

## Related Issues

List the related issues to this change. For example, `Closes #xyz`

## Test Plan

Please describe the exact steps you followed to test your change. Be as clear as possible so a reviewer can follow the same steps. List what UI interactions are needed, or if there are automated tests then list what should be run. For example:

1. Go to: https://scout.tsdataclinic.com/explore/NYC
2. Advance through screen using Tab key to 1st dataset link.
3. Unable to see where I was on the page as there's no outline to indicate focus.
4. Added outline to dataset link to allow for visual tracking of focused element.

## Checklist Before Requesting a Review

- [ ] I have performed a self-review of my code
- [ ] My code follows the Style Guidelines and Best Practices outlined in the project wiki
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made changes to the documentation, if applicable
- [ ] My change generates no new warnings or failed tests
- [ ] If it is a core feature, I have added thorough tests
- [ ] I have implemented analytics, if applicable

2022-08-04 21:00 UTC, jps327 requested changes
Just some minor edits!

2022-08-04 21:00 UTC, jps327 commented on packages/frontend/src/components/Dataset/Dataset.scss
> +    &:focus-visible{
Remember to keep your code following any patterns you already see in the codebase you're editing. In this case, remember to add a space before the opening curly braces.

2022-08-04 21:00 UTC, jps327 commented on packages/frontend/src/components/Dataset/Dataset.scss
> +      outline:3px solid #000;
Similar to the last comment, remember to stick to existing code conventions. In this case, adding a space in between the colon and the 3px

2022-08-05 19:15 UTC, Detroit-the-Dev commented
Hey Pablo!

Fixed the spacing to be in conformance with codebase conventions.

Thanks!

2022-08-11 13:55 UTC, jps327 approved these changes
Thanks!

2022-08-11 13:55 UTC, merged